name: Build libmagic library (macOS - ARM64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: libmagic compilation
        run: |
          cd assets/file ; autoreconf -f -i ; ./configure --disable-silent-rules ; make -j4
      - name: libmagic artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "libmagic library"
          path: assets/file/src/.libs/libmagic.1.dylib
