name: Build Project (Debug)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest, macos-13]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Setup Mono (Unix)
        if: matrix.runs-on == 'ubuntu-latest'
        run: sudo apt install mono-complete
      - name: Setup Mono (macOS)
        if: matrix.runs-on == 'macos-latest'
        run: brew install mono
      - name: Solution Compilation (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: ./tools/build.cmd Debug -p:ContinuousIntegrationBuild=true
      - name: Solution Compilation (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: make dbg-ci
      - name: Testing
        if: matrix.runs-on != 'macos-latest'
        run: dotnet test --no-build --configuration Debug
      - name: Testing (macOS ARM64)
        if: matrix.runs-on == 'macos-latest'
        run: dotnet test --no-build --configuration Debug --framework net8.0
        
